## 3rd Party Client Related
client:
    gui_language: 'english'
    client: 'PGSharp' # Support 'PGSharp' | Pokemod' | 'HAL' | 'Polygon' | 'Polygon Paid'. 
    team_rocket_blastoff: false # Set to false if not using Pokemod's Team Rocket Blastoff (Explorer Feature) or Polygon's Rocket Battle Autowin | PGSharp user set this to false
    instant_spin: false # Set to false if not using Pokemod's Instant Spin (Explorer Feature) or Polygon's Pokestop Autospin | PGSharp user set this to false
    skip_encounter_intro: false # Set to false if not using Pokemod's Skip Encounter Intro | Polygon users please set this to true | PGSharp user set this to false
    encounter_iv: true # Set to false if not using Pokemod's Show Encounter IV or Polygon's nameplate | PGSharp Paid User please do not hide PGSharp if you enable this option
    transfer_on_catch: false # Is transfer on catch enabled in Pokemod? (Please enable instant catch too) | Polygon Users please set this to true (Enabled by default for enhanced catch) | PGSharp users, this option is call Quick Catch. Enable if you use quick catch. Use Pokemon Management options to transfer Pokemon when bag is full (please test that it work for you). Else set this option as false. 
    manual_set_resolution: false # Bot will attempt to auto resize screen resolution if set to false. If you prefer to resize it manually, set this to true
    auto_route: false # Are you using auto walk or gpx? PGSharp Free users please set this to false. PGSharp Paid users please use auto walk or gpx. 
    screen_offset: 0 # Some phones, especially those with front camera build right on the screen in the center, your Pokemon Go screen will be shifted slight downwards. To test if you need to add a number here, set clear_item_on_start to true, and see if the name of the items are correctly captured. If not, set a number here. (try 80)
    navigation_offset: 0 # Some phones have on screen navigation buttons that cannot be removed. Set this to the height of the navigation button to hide it
    screenshot_shift: 0 # When taking screenshot of Pokemon Go during running of RAB, black bar is seen at top and bottom of the screenshot. Set a number to the first visible pixel that's not black
    auto_offset: true # RAB will attempt to give you a screen_offset value. After you got this vlaye, Use this value at screen_offset above and set auto_offset to off
    auto_goplus: false # Do you have go plus that can connect all the time? (Example HAL has auto pokemon go plus)
    hyper_mode: false

## discord Webhook, Currently only support sending to Discord
## Set what notification you want to get from RAB
discord:
    enabled: false # Do you want to enable sending to discord
    webhook_url: '' # Refer to Create Webhook at https://docs.gitlab.com/ee/user/project/integrations/discord_notifications.html
    notify_encountered: false # Notify shiny/max iv/pvp iv when encountered it.
    notify_caught_fled: true # Notify shiny/max iv/pvp iv when caught or flee. Depend on which client you are using and the settings you used (example: transfer on catch), you will get notified too if RAB is unable to determine if this poke has fled or caught
    notify_shiny: true
    notify_max_iv: true
    notify_pvp_iv: true
    notify_all_caught: false

## Setting for Polygon (Paid Enchancer) to connect to the computer
## Under Polygon Advance settings, set Send data to custom backend to true
## Backend IP Address to your computer's IP
## Make sure both Phone and Computer are on the same network
network:
    host: '0.0.0.0' # local computer's hostname or IP address (Suggest to leave it as 0.0.0.0).
    port: 5120 # The port used by the server, must be different port for each device

## Telegram snipe/shiny check
## Get your own api_id and api_hash from https://my.telegram.org, under API Development
## Default vaules are exmaple and will not work
telegram:
    enabled: false # Enable it if you want to use either Shiny Check or Pokemon Snip function
    telegram_api_id: 0 # Numbers
    telegram_api_hash: ''
    proxy: '' # Optional, for those who can't run telegram in their network

shiny_check:
    enabled: false
    auto_catch: true  # let the bot to auto-catch
    default_location: [0,0]  # initial cooldown timing will be based on this location if cannot get from phone
    mon_to_check: []  # 'Croagunk', 'Mareep', 'Burmy' list of Pokemon to check. Leave it blank to check all
    mon_to_ignore: ['Weedle', 'Sentret', 'Seedot', 'Castform', 'Turtwig', 'Mankey', 'Lillipup', 'Rhyhorn', 'Patrat',
                    'Vulpix', 'Piplup', 'Onix', 'Bulbasaur', 'Abra', 'Swinub', 'Gastly', 'Chimchar', 'Drifloon']
    mon_at_high_location: ['Burmy']
    src_telegram: [] # Telegram ID Example: [-10012345678, -1003254618, '@myChannel']

# polygon users, please disable Auto Release Module for pvp snipe to work
snipe:
    enabled: false
    snipe_max_cd: 12 # Only Snip if CD is below this timing in mins, set above 120 to snipe as long as it appear
    snipe_list: { 'Skuntank': { 'type': 'gl', 'rating': 99 }, 'Crustle': { 'type': 'gl', 'rating': 99 }, 'Granbull': { 'type': 'ul', 'rating': 99, 'shiny_check': true }, 'Mantine': { 'type': 'iv100'} } # The final form of pokemon with pvp rate that you want to catch, type option: gl, ul, pvp, iv100. pvp means any pvp league, add shiny_check if you only want to catch if its shiny 
    snipe_any_100iv: false # For testing if snipe works
    auto_catch: true # let the bot to auto-catch
    default_location: [0,0]  # Set this to the first location in your default route
    mon_at_high_location: ['Burmy']
    src_telegram: [] # Telegram ID Example: [-10012345678, -1003254618, '@myChannel']
    default_route_name: 'Your Route Name' # Bot will start from this route after snipe

quest:
    enable_check_quest: true
    power_up_lvl: 5 # How many times to you want to powerup a level 1 pokemon on catch to clear power up quest. Default is 5. Set to 0 if you do not want to do any power up.
    clear_quest_interval: 10
    last_quest_quit_today: '' # A short name that will trigger a quit from quest Today page. This will save time.
    last_quest_quit: '' # A short name that will trigger a quit from quest special page. This will save time.

## Screenshots
screenshot:
    start: false
    catch: false
    shiny: false
    appraisal: false
    exception: false

# Spin Pokestop
spin_pokestop: true # Spin pokestop if instant spin is not enabled?

## Catch Related
## Options related to keeping or releasing pokemons here are also applied to Pokemon Management options
catch:
    enable_keep_mon: true # For Polygon users, these settings will apply to Pokemon Management options
    min_atk: 15
    min_def: 15
    min_sta: 15
    or_condition: false # Set to true to use ((atk and def and sta) or min lvl). Default condition: and
    min_lvl: 1
    enable_keep_shiny: true
    keep_strong_shadow: false # Strong shdaow is defined as IV >= 86 or Atk IV = 0 
    keep_legendary: true # inclusive of mythical Pokemon
    keep_lucky: true # pokemon management option
    keep_event: true # pokemon management option
    high_far_pokemon: ['Zubat', 'Golbat', 'Magmar', 'Aerodactyl', 'Tentacruel', 'Tangela', 'Electabuzz', 'Abra', 
                        'Lapras', 'Yanma', 'Sawk', 'Growlithe', 'Weepinbell', 'Porygon', 'Magmar', 'Snorlax', 
                        'Doduo', 'Mantine', 'Arbok', 'Jynx', 'Dunsparce', 'Hariyama', 'Lickilicky', 'Shuppet', 
                        'Gastly', 'Hoppip', 'Hitmonlee', 'Trubbish', 'Skiploom', 'Dragonair'] # List of Pokemon that requires high throw in order to catch them
    mon_to_keep: ['Gible','Mewtwo','Vullaby','Scraggy','Pawniard','Deino', 'Gengar', 'Axew', 'Victini', 'Spiritomb', 'Cottonee', 'Pawniard']
    shadow_mon_to_keep: ['Skarmory']
    only_shiny: false # NEW OPTION: Only catch shiny. Flee for the rest, note that there will be a chance of RAB clicking that same poke again....
    delay_before_appraisal: 1.0 # NEW OPTION: Number of secs of delay before doing appraisal. Increase this value if you often see misclick when RAB trying to do appraisal
    stop_at_ball: 10 # NEW OPTION: Polygon Paid Only. Stop catching when balls reach this number
    resume_at_ball: 100  # NEW OPTION: Polygon Paid Only. Start catching when balls reach this number
    catchpoke_every_x_spin: 5 # NEW OPTION: Polygon Paid Only. Try Catch a poke after every x spin (In Spin Mode). This is to help bot to refresh item list
    go_after_shiny: true # NEW OPTION: Polygon Paid Only. If Polygon alert shiny, teleport and try catch it
    go_after_100IV: true # NEW OPTION: Polygon Paid Only. If Polygon alert 100IV, teleport and try catch
    shiny_mode: false # NEW OPTION: Polygon Paid Only. RAB will keep walking until shiny appear and catch it.

berry_selection:
    use_berry: true # Default auto use berries. Set to false if you do not want to use berries
    shiny_or_high_lvl: ['golden razz berry', 'razz berry']
    mid_lvl: ['nanab berry', 'razz berry']
    low_lvl_or_unknown: ['razz berry', 'nanab berry']

ball_selection:
    select_ball: true # Default auto select ball. Set to false to use default ball without selecting
    shiny_or_high_lvl: ['ultra ball', 'great ball', 'poke ball']
    mid_lvl: ['great ball', 'poke ball', 'ultra ball']
    low_lvl_or_unknown: ['poke ball', 'great ball', 'ultra ball']

## Keep Pokemon according to PvP rating
## gl_to_keep and ul_to_keep is list of Pokedex number of Pokemons to keep if they meet conditions. 
## Example [3,6,9] Empty box to keep all that meet conditions
## Options related to keeping or releasing pokemons here are also applied to Pokemon Management options
pvp:
    enable_keep_pvp: true # For Polygon users, these settings will apply to Pokemon Management options
    gl_to_keep: ['Aerodactyl','Skarmory','Cottonee', 'Minccino', 'Cubchoo']
    gl_rating: 99.0
    gl_cp: 1450
    ul_to_keep: []
    ul_rating: 99.0
    ul_cp: 2400

## Pokemon Inventory Management
## Release will be base on rules set in catch and pvp above
## Shiny, Legendary and Mythical Pokemon will be kept during final confirmation. If your 3rd party app has Transfer any pokemon option, make sure it is DISABLED.
## Please do a test run by setting manage_poke_on_start to true and ensure it perform as it should before trusting this module! 
poke_management:
    enable_poke_management: true # call it when Pokemon Storage is full message appear?
    manage_poke_on_start: false # call it right at the start?
    inventory_iv: false # check iv at mon details page (Currently only support PGSharp Paid)
    stop_check_at: 50 # Total no. of pokemon to look through before quiting the page

## Item Management
item_management:
    enable_item_management: true
    item_management_interval: 60 # In mins
    clear_item_on_start: false
    reset_bagfull_interval: 20 # In mins
    auto_max: false # New HAL Feature, items are auto maxed, just need to confirm delete without press and hold
    last_item_quit: '' # Name of item that will trigger RAB to quit scrolling item page. This will save time.

## Item Options
item_config:
    Potion: true
    Super Potion: true
    Hyper Potion: false
    Max Potion: false
    Revive: false
    Max Revive: false
    Incense: false
    Pok√© Ball: false
    Great Ball: false
    Ultra Ball: false
    Razz Berry: false
    Nanab Berry: false
    Pinap Berry: false
    Golden Razz Berry: false

## Advance
## Additional values to help those having issue such as not detecting main map
## DO NOT CHANGE ANY OF THESE VALUES UNLESS INSTRUCTED TO DO SO
